var Woogeen=Woogeen||{};
Woogeen.EventDispatcher=function(d){var c={};d.dispatcher={};d.dispatcher.eventListeners={};c.addEventListener=function(c,e){void 0===d.dispatcher.eventListeners[c]&&(d.dispatcher.eventListeners[c]=[]);d.dispatcher.eventListeners[c].push(e)};c.removeEventListener=function(c,e){var j;j=d.dispatcher.eventListeners[c].indexOf(e);-1!==j&&d.dispatcher.eventListeners[c].splice(j,1)};c.dispatchEvent=function(c){for(var e in d.dispatcher.eventListeners[c.type])if(d.dispatcher.eventListeners[c.type].hasOwnProperty(e))d.dispatcher.eventListeners[c.type][e](c)};return c};
Woogeen.WoogeenEvent=function(d){var c={};c.type=d.type;return c};Woogeen.RoomEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.streams=d.streams;return c};Woogeen.StreamEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.stream=d.stream;c.msg=d.msg;return c};Woogeen.PublisherEvent=function(d){return Woogeen.WoogeenEvent(d)};Woogeen.ServerEvent=function(d){return Woogeen.WoogeenEvent(d)};Woogeen.ChatEvent=function(d){var c=Woogeen.WoogeenEvent(d);c.senderId=d.senderId;c.peerId=d.peerId;return c};
Woogeen.DataEvent=function(d){var c=Woogeen.WoogeenEvent(d);d.data&&(c.data=d.data);d.senderId&&(c.senderId=d.senderId);d.peerId&&(c.peerId=d.peerId);return c};Woogeen.RecorderEvent=function(d){var c=Woogeen.WoogeenEvent(d);d.audio&&(c.audio=d.audio);return c};Woogeen=Woogeen||{};
Woogeen.Error={STREAM_LOCAL_ACCESS_DENIED:{code:1101,message:"Cannot access to camera or micphone."},P2P_CONN_SERVER_UNKNOWN:{code:2100,message:"Server unknown error."},P2P_CONN_SERVER_UNAVAILABLE:{code:2101,message:"Server is unavaliable."},P2P_CONN_SERVER_BUSY:{code:2102,message:"Server is too busy."},P2P_CONN_SERVER_NOT_SUPPORTED:{code:2103,message:"Method has not been supported by server"},P2P_CONN_CLIENT_UNKNOWN:{code:2110,message:"Client unknown error."},P2P_CONN_CLIENT_NOT_INITIALIZED:{code:2111,message:"Connection is not initialized."},
P2P_CONN_AUTH_UNKNOWN:{code:2120,message:"Authentication unknown error."},P2P_CONN_AUTH_FAILED:{code:2121,message:"Wrong username or token."},P2P_MESSAGING_TARGET_UNREACHABLE:{code:2201,message:"Remote user cannot be reached."},P2P_CHATROOM_ATTENDEE_EXCEED:{code:2301,message:"Exceed room's limitation"},P2P_CHATROOM_PEER_NOT_FOUND:{code:2302,message:"Peer not found. Only one client in the room."}};Woogeen=Woogeen||{};
Woogeen.Peer=function(d){var c=Woogeen.EventDispatcher({}),g=null,e={},j={},k={},i=[],o=null,B={optional:[{DtlsSrtpKeyAgreement:"true"}]},C={mandatory:{OfferToReceiveAudio:!0,OfferToReceiveVideo:!0}},u=null;d&&(u={},d.iceServers&&(u.iceServers=function(a){for(var b=[],f=0;f<a.length;f++){var h=a[f];if("[object Array]"==Object.prototype.toString.apply(h.urls))for(var c=0;c<h.urls.length;c++)b.push({url:h.urls[c],username:h.username,credential:h.credential});else b.push({url:h.urls,username:h.username,
credential:h.credential})}return b}(d.iceServers)));var p=function(a){var b;b=null;try{b=v(a)}catch(f){console.log("Decode room failed. It may be an invalid room token.")}if(b=b&&b.host&&b.id?b:null){a=b.id;a=k[a]?k[a].peer:void 0;return a?a.id:null}return a},l=function(a,b){if(a.state==6||a.state==5){a.sendDataChannel&&a.sendDataChannel.close();a.receiveDataChannel&&a.receiveDataChannel.close();a.connection&&a.connection.iceConnectionState!=="closed"&&a.connection.close();if(a.state!==1){a.state=
1;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-stopped",peerId:a.id,senderId:b}))}}},D=function(){c.dispatchEvent(Woogeen.ServerEvent({type:"server-connected"}))},E=function(){for(var a in e){l(e[a],o);delete e[a]}c.dispatchEvent(Woogeen.ServerEvent({type:"server-disconnected"}))},F=function(a){var b=e[a];if(!b){m(a);b=e[a]}console.log("Invite state:"+b.state);if(b.state===1){e[a].state=4;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-invited",senderId:a}))}else(b.state===5||b.state===2||b.state===
6)&&x(b.localStream,b)},G=function(a){var b=e[a];if(b&&b.connection){b.sendDataChannel&&b.sendDataChannel.close();b.receiveDataChannel&&b.receiveDataChannel.close();b.connection.close();delete e[a]}c.dispatchEvent(Woogeen.ChatEvent({type:"chat-denied",senderId:a}))},H=function(a){var b=e[a];if(b&&b.connection){l(b,a);delete e[a]}},K=function(a,b){var f=e[a];f&&f.state===5&&(f.connection||q(f));console.log("S->C: "+JSON.stringify(b));if(b.type==="offer")I(f,{message:b});else if(b.type==="answer")J(f,
{message:b});else if(b.type==="candidate"&&f&&(f.state===5||f.state===6||f.state===7)){var h=new RTCIceCandidate({candidate:b.candidate,sdpMid:b.sdpMid,sdpMLineIndex:b.sdpMLineIndex});if(f.localDescSet&&f.remoteDescSet)if(i.length!==0){i.push(h);for(h=0;h<i.length;h++)f.connection.addIceCandidate(i[h],r,s);i=[]}else try{f.connection.addIceCandidate(h,r,s)}catch(c){console.error("Add remote ICE candidate failed. Error: "+c.message)}else i.push(h)}},L=function(a,b){j[b.streamId]=b.type;console.log("remote stream lable:"+
b.streamId+",type:"+j[b.streamId])},M=function(a){e[a]||m(a);if(e[a].state===1&&q(e[a])){e[a].state=2;c.dispatchEvent(Woogeen.ChatEvent({type:"chat-ready",peerId:a}))}},N=function(){c.dispatchEvent(Woogeen.ChatEvent({type:"chat-wait"}))},O=function(a){o=a},P=function(a){console.log("Negotiation is needed");if(a.negotiationNeed){a.localDescSet=false;a.remoteDescSet=false;a.connection.createOffer(function(b){b.sdp=t(b.sdp);a.connection.setLocalDescription(b,function(){a.localDescSet=true;console.log("Set local descripiton successfully.");
g.sendSignalMessage(a.id,b);a.state=7},function(a){console.log("Set local description failed. Message: "+JSON.stringify(a))})},function(){console.log("Create offer failed.")})}a.negotiationNeed=false},I=function(a,b){if(a&&(a.state===3||a.state===2||a.state===6||a.state===7)){a.state=5;a.localDescSet=false;a.remoteDescSet=false;if(a.localStream!==null){w(a.localStream,a);a.connection.addStream(a.localStream.stream)}a.connection.setRemoteDescription(new RTCSessionDescription(b.message),function(){a.remoteDescSet=
true;console.log("Set remote descripiton successfully.");a.connection.createAnswer(function(b){b.sdp=t(b.sdp);a.connection.setLocalDescription(b,function(){a.localDescSet=true;console.log("Set local description successfully.");g.sendSignalMessage(a.id,b);console.log("Sent answer.");if(i.length!=0){for(var h=0;h<i.length;h++){console.log("remoteIce, length:"+i.length+", current:"+h);(a.state===6||a.state===5)&&a.connection.addIceCandidate(i[h],r,s)}i=[]}a.state=6},function(a){console.error("Error occurred while setting local description. Error message:"+
a)})},function(){console.log("Create answer failed.")},C)},function(a){console.log("Set remote description failed. Message: "+JSON.stringify(a))})}},J=function(a,b){a&&(a.state===5||a.state===7)&&a.connection.setRemoteDescription(new RTCSessionDescription(b.message),function(){a.remoteDescSet=true;a.state=6;console.log("Set remote descripiton successfully.");if(i.length!=0){for(var b=0;b<i.length;b++){console.log("remoteIce, length:"+i.length+", current:"+b);(a.state===6||a.state===5)&&a.connection.addIceCandidate(i[b],
r,s)}i=[]}},function(a){console.log("Set remote description failed. Message: "+a)})},r=function(){console.log("Add ice candidate success.")},s=function(a){console.log("Add ice candidate failed. Error: "+a)},q=function(a){if(!a||a.connection)return true;try{a.localDescSet=false;a.remoteDescSet=false;a.negotiationNeed=false;a.connection=new RTCPeerConnection(u,B);a.connection.onicecandidate=function(b){b.candidate&&g.sendSignalMessage(a.id,{type:"candidate",candidate:b.candidate.candidate,sdpMid:b.candidate.sdpMid,
sdpMLineIndex:b.candidate.sdpMLineIndex})};a.connection.onaddstream=function(b){console.log("Remote stream added.");a.state=6;b=Woogeen.StreamEvent({type:"stream-subscribed",stream:{stream:b.stream,type:j[b.stream.label]||"video"}});c.dispatchEvent(b);c.dispatchEvent(Woogeen.ChatEvent({type:"chat-started",peerId:a.id}))};a.connection.onremovestream=function(){console.log("Remote stream removed.");var a=Woogeen.StreamEvent({type:"stream-removed"});c.dispatchEvent(a)};a.connection.oniceconnectionstatechange=
function(){if(a){console.log("Ice connection state changed. State: "+a.connection.iceConnectionState);if(a.connection.iceConnectionState==="closed"&&a.state===6){l(a,a.id);g.sendVideoStopped(a.id);delete e[a.id]}a.connection.iceConnectionState==="disconnected"&&console.log("Ice connection state changed. State: "+a.connection.iceConnectionState);if(a.connection.iceConnectionState==="connected")a.state=6;if(a.connection.iceConnectionState==="completed")a.state=6}};a.connection.onnegotiationneeded=function(){P(a)};
a.connection.onsignalingstatechange=function(){if(a.connection.signalingState==="closed"){l(a,a.id);delete e[a.id]}};a.connection.ondatachannel=function(b){a.receiveDataChannel=b.channel;a.receiveDataChannel.onmessage=function(b){b=Woogeen.DataEvent({type:"data-received",senderId:a.id,data:b.data});c.dispatchEvent(b)};a.receiveDataChannel.onerror=function(a){console.log("receiveDataChannel Data Channel Error:",a)};a.receiveDataChannel.onclose=function(){y()}}}catch(b){console.log("Failed to create PeerConnection, exception: "+
b.message);return false}return true},Q=function(a){e[a]||m(a);var b=e[a];try{b.negotiationNeed=true;b.state=7;b.sendDataChannel=b.connection.createDataChannel("sendDataChannel",null)}catch(f){b.negotiationNeed=false;console.log("Failed to create SendDataChannel, exception: "+f.message)}b.sendDataChannel.onerror=function(a){console.log("sendDataChannel Data Channel Error:",a)};b.sendDataChannel.onopen=function(){var b=Woogeen.DataEvent({type:"data-opened",peerId:a});c.dispatchEvent(b);console.log("Data Channel is opened")};
b.sendDataChannel.onclose=function(){y(a)}},m=function(a){e[a]||(e[a]={state:1,id:a})},v=function(a){return room=JSON.parse(a)},w=function(a,b){if(a!==null){var f="audio";a.hasVideo()?f="video":a.hasScreen()&&(f="screen");g.sendVideoType(b.id,{streamId:a.stream.label,type:f})}},x=function(a,b){if(b){b.localStream=a;q(b);if(a!==null&&(b.state===5||b.state===4||b.state===2||b.state===6)){if(b.localStream){w(a,b);b.connection.addStream(a.stream)}b.connection.createOffer(function(a){a.sdp=t(a.sdp);b.connection.setLocalDescription(a,
function(){b.localDescSet=true;console.log("Set local descripiton successfully.");g.sendSignalMessage(b.id,a);b.state=5},function(a){console.log("Set local description failed. Message: "+JSON.stringify(a))})},function(){console.log("Create offer failed.")})}}},z=function(a){if(!g)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;if(a){var b=e[a];if(b){g.sendVideoStopped(b.id);l(b,o);delete e[a]}}else for(var f in e){b=e[f];g.sendVideoStopped(b.id);l(b,o);delete e[b.id]}},A=function(a){var b=k[a];
if(b){z(b.peer.id);if(!g)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;g.sendLeaveRoom(a);delete k[a]}},y=function(){console.log("Data Channel is closed")},t=function(a){for(var b=a.split("\r\n"),f=0;f<b.length;f++)if(b[f].search("m=audio")!==-1){var c=f;break}if(c===null)return a;for(f=0;f<b.length;f++)if(b[f].search("opus/48000")!==-1){var e=n(b[f],/:(\d+) opus\/48000/i);if(e){for(var a=b,f=c,d=b[c].split(" "),g=[],i=0,j=0;j<d.length;j++){i===3&&(g[i++]=e);d[j]!==e&&(g[i++]=d[j])}e=g.join(" ");
a[f]=e}break}a=c;f=b[a].split(" ");for(e=b.length-1;e>=0;e--)if(d=n(b[e],/a=rtpmap:(\d+) CN\/\d+/i)){d=f.indexOf(d);d!==-1&&f.splice(d,1);b.splice(e,1)}b[a]=f.join(" ");a=c;f=b[a].split(" ");for(e=b.length-1;e>=0;e--)if(d=n(b[e],/a=rtpmap:(\d+) ISAC\/\d+/i)){d=f.indexOf(d);d!==-1&&f.splice(d,1);b.splice(e,1)}b[a]=f.join(" ");a=c;f=b[a].split(" ");for(e=b.length-1;e>=0;e--)if(d=n(b[e],/a=rtpmap:(\d+) PCMU\/\d+/i)){d=f.indexOf(d);d!==-1&&f.splice(d,1);b.splice(e,1)}b[a]=f.join(" ");a=c;f=b[a].split(" ");
for(e=b.length-1;e>=0;e--)if(d=n(b[e],/a=rtpmap:(\d+) PCMA\/\d+/i)){d=f.indexOf(d);d!==-1&&f.splice(d,1);b.splice(e,1)}b[a]=f.join(" ");a=b[c].split(" ");for(f=b.length-1;f>=0;f--)if(e=n(b[f],/a=rtpmap:(\d+) telephone-event\/\d+/i)){e=a.indexOf(e);e!==-1&&a.splice(e,1);b.splice(f,1)}b[c]=a.join(" ");a=b.join("\r\n");a=a.replace(/a=fmtp:\d+.*\r\n/ig,"");return a=a.replace(/a=rtpmap:(\d+) opus\/48000\/2\r\n/i,"a=rtpmap:$1 opus/48000/2\r\na=fmtp:$1 minptime=10 stereo=1; sprop-stereo=1\r\n")},n=function(a,
b){var f=a.match(b);return f&&f.length==2?f[1]:null};c.connect=function(a,b,f){g=new Gab(a,b,f);g.onConnected=D;g.onDisconnected=E;g.onVideoStopped=H;g.onVideoDenied=G;g.onVideoInvitation=F;g.onVideoSignal=K;g.onVideoType=L;g.onChatWait=N;g.onChatReady=M;g.onAuthenticated=O};c.disconnect=function(){g&&g.finalize();g=null};c.publish=function(a,b,f){b=p(b);if(!b)throw Woogeen.Error.P2P_CHATROOM_PEER_NOT_FOUND;e[b]||m(b);var c=e[b];if(c.state===1||c.state===6){if(!g)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;
e[b]||m(b);e[b].state=3;g.sendVideoInvitation(b);if(f===1)c.state=5}else if(f===1)c.state=3;x(a,c)};c.unpublish=function(a,b){b=p(b);if(!b)throw Woogeen.Error.P2P_CHATROOM_PEER_NOT_FOUND;e[b]&&e[b].connection.removeStream(a.stream)};c.deny=function(a){if(e[a]&&e[a].state===4){if(!g)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;g.sendVideoDenied(a);delete e[a]}};c.stop=z;c.joinRoom=function(a,b){var c=v(a);if(!g)throw Woogeen.Error.P2P_CONN_CLIENT_NOT_INITIALIZED;g.onChatReady=function(a){e[a]||
m(a);a=e[a];a.state=2;a.roomId=c.id;a.localStream=b;a.sendDataChannel&&a.sendDataChannel.close();a.receiveDataChannel&&a.receiveDataChannel.close();q(a);k[c.id]={peer:a}};g.sendJoinRoom(c.id)};c.leaveRoom=function(a){if(a){room=v(a);A(room.id)}else for(var b in k)A(k[b])};c.sendData=function(a,b){var c=p(b);(c=e[c])&&(c.sendDataChannel.readyState=="open"?c.sendDataChannel.send(a):console.log("Data channel send data faliure"))};c.createDataChannel=function(a){Q(p(a))};c.switchStream=function(a,b,c){var d=
e[c];a!==null&&d.connection.removeStream(a.stream);w(b,d);d.connection.addStream(b.stream);d.localStream=b;d.localDescSet=false;d.remoteDescSet=false;d.connection.createOffer(function(a){a.sdp=t(a.sdp);d.connection.setLocalDescription(a,function(){d.localDescSet=true;console.log("Set local descripiton successfully.");g.sendSignalMessage(d.id,a);d.state=7},function(a){console.log("Set local description failed. Message: "+JSON.stringify(a))})},function(){console.log("Create offer failed.")})};return c};
