/*
 MIT
*/
var Url=require("url"),spawn=require("child_process").spawn,fs=require("fs"),XMLHttpRequest=function(){var b=this,o=require("http"),p=require("https"),j,c,e={},n={"User-Agent":"node.js",Accept:"*/*"},h=!1,l=!1,m=n;this.UNSENT=0;this.OPENED=1;this.HEADERS_RECEIVED=2;this.LOADING=3;this.DONE=4;this.readyState=this.UNSENT;this.onreadystatechange=null;this.responseXML=this.responseText="";this.statusText=this.status=null;this.open=function(a,b,f,c,g){e={method:a,url:b.toString(),async:"boolean"!==typeof f?
!0:f,user:c||null,password:g||null};this.abort();i(this.OPENED)};this.setRequestHeader=function(a,b){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: setRequestHeader can only be called when state is OPEN";if(h)throw"INVALID_STATE_ERR: send flag is true";m[a]=b};this.getResponseHeader=function(a){return this.readyState>this.OPENED&&c.headers[a]&&!l?c.headers[a]:null};this.getAllResponseHeaders=function(){if(this.readyState<this.HEADERS_RECEIVED||l)return"";var a="",b;for(b in c.headers)a+=
b+": "+c.headers[b]+"\r\n";return a.substr(0,a.length-2)};this.send=function(a){if(this.readyState!=this.OPENED)throw"INVALID_STATE_ERR: connection must be opened before send() is called";if(h)throw"INVALID_STATE_ERR: send has already been called";var k=!1,f=Url.parse(e.url);switch(f.protocol){case "https:":k=!0;case "http:":var d=f.hostname;break;case void 0:case "":d="localhost";break;default:throw"Protocol not supported.";}var g=f.port||(k?443:80),f=f.pathname+(f.search?f.search:"");this.setRequestHeader("Host",
d);if(e.user){"undefined"==typeof e.password&&(e.password="");var n=new Buffer(e.user+":"+e.password);m.Authorization="Basic "+n.toString("base64")}"GET"==e.method||"HEAD"==e.method?a=null:a&&(this.setRequestHeader("Content-Length",Buffer.byteLength(a)),m["Content-Type"]||this.setRequestHeader("Content-Type","text/plain;charset=UTF-8"));d={host:d,port:g,path:f,method:e.method,headers:m};l=!1;if(!e.hasOwnProperty("async")||e.async){k=k?p.request:o.request;h=!0;if("function"===typeof b.onreadystatechange)b.onreadystatechange();
j=k(d,function(a){c=a;c.setEncoding("utf8");i(b.HEADERS_RECEIVED);b.status=c.statusCode;c.on("data",function(a){if(a)b.responseText=b.responseText+a;h&&i(b.LOADING)});c.on("end",function(){if(h){i(b.DONE);h=false}});c.on("error",function(a){b.handleError(a)})}).on("error",function(a){b.handleError(a)});a&&j.write(a);j.end()}else{g=".node-xmlhttprequest-sync-"+process.pid;fs.writeFileSync(g,"","utf8");a="var http = require('http'), https = require('https'), fs = require('fs');var doRequest = http"+
(k?"s":"")+".request;var options = "+JSON.stringify(d)+";var responseText = '';var req = doRequest(options, function(response) {response.setEncoding('utf8');response.on('data', function(chunk) {responseText += chunk;});response.on('end', function() {fs.writeFileSync('"+g+"', 'NODE-XMLHTTPREQUEST-STATUS:' + response.statusCode + ',' + responseText, 'utf8');});response.on('error', function(error) {fs.writeFileSync('"+g+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');});}).on('error', function(error) {fs.writeFileSync('"+
g+"', 'NODE-XMLHTTPREQUEST-ERROR:' + JSON.stringify(error), 'utf8');});"+(a?"req.write('"+a.replace(/'/g,"\\'")+"');":"")+"req.end();";for(syncProc=spawn(process.argv[0],["-e",a]);""==(b.responseText=fs.readFileSync(g,"utf8")););syncProc.stdin.end();fs.unlinkSync(g);b.responseText.match(/^NODE-XMLHTTPREQUEST-ERROR:/)?(a=b.responseText.replace(/^NODE-XMLHTTPREQUEST-ERROR:/,""),b.handleError(a)):(b.status=b.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:([0-9]*),.*/,"$1"),b.responseText=b.responseText.replace(/^NODE-XMLHTTPREQUEST-STATUS:[0-9]*,(.*)/,
"$1"),i(b.DONE))}};this.handleError=function(a){this.status=503;this.statusText=a;this.responseText=a.stack;l=!0;i(this.DONE)};this.abort=function(){j&&(j.abort(),j=null);m=n;this.responseXML=this.responseText="";l=!0;if(this.readyState!==this.UNSENT&&(this.readyState!==this.OPENED||h)&&this.readyState!==this.DONE)h=!1,i(this.DONE);this.readyState=this.UNSENT};var d={};this.addEventListener=function(a,b){a in d||(d[a]=[]);d[a].push(b)};var i=function(a){b.readyState=a;if("function"===typeof b.onreadystatechange)b.onreadystatechange();
if("readystatechange"in d)for(var a=d.readystatechange.length,c=0;c<a;c++)d.readystatechange[c].call(b)}};
var CryptoJS=CryptoJS||function(e,c){var l={},a=l.lib={},b=a.Base=function(){function h(){}return{extend:function(a){h.prototype=this;var d=new h;a&&d.mixIn(a);d.$super=this;return d},create:function(){var h=this.extend();h.init.apply(h,arguments);return h},init:function(){},mixIn:function(h){for(var a in h)h.hasOwnProperty(a)&&(this[a]=h[a]);h.hasOwnProperty("toString")&&(this.toString=h.toString)},clone:function(){return this.$super.extend(this)}}}(),g=a.WordArray=b.extend({init:function(h,a){h=
this.words=h||[];this.sigBytes=a!=c?a:4*h.length},toString:function(h){return(h||f).stringify(this)},concat:function(h){var a=this.words,d=h.words,g=this.sigBytes,h=h.sigBytes;this.clamp();if(g%4)for(var b=0;b<h;b++)a[g+b>>>2]|=(d[b>>>2]>>>24-8*(b%4)&255)<<24-8*((g+b)%4);else if(65535<d.length)for(b=0;b<h;b+=4)a[g+b>>>2]=d[b>>>2];else a.push.apply(a,d);this.sigBytes+=h;return this},clamp:function(){var h=this.words,a=this.sigBytes;h[a>>>2]&=4294967295<<32-8*(a%4);h.length=e.ceil(a/4)},clone:function(){var h=
b.clone.call(this);h.words=this.words.slice(0);return h},random:function(h){for(var a=[],d=0;d<h;d+=4)a.push(4294967296*e.random()|0);return g.create(a,h)}}),j=l.enc={},f=j.Hex={stringify:function(h){for(var a=h.words,h=h.sigBytes,d=[],b=0;b<h;b++){var g=a[b>>>2]>>>24-8*(b%4)&255;d.push((g>>>4).toString(16));d.push((g&15).toString(16))}return d.join("")},parse:function(a){for(var d=a.length,b=[],i=0;i<d;i+=2)b[i>>>3]|=parseInt(a.substr(i,2),16)<<24-4*(i%8);return g.create(b,d/2)}},k=j.Latin1={stringify:function(a){for(var d=
a.words,a=a.sigBytes,b=[],g=0;g<a;g++)b.push(String.fromCharCode(d[g>>>2]>>>24-8*(g%4)&255));return b.join("")},parse:function(a){for(var d=a.length,b=[],i=0;i<d;i++)b[i>>>2]|=(a.charCodeAt(i)&255)<<24-8*(i%4);return g.create(b,d)}},d=j.Utf8={stringify:function(a){try{return decodeURIComponent(escape(k.stringify(a)))}catch(d){throw Error("Malformed UTF-8 data");}},parse:function(a){return k.parse(unescape(encodeURIComponent(a)))}},i=a.BufferedBlockAlgorithm=b.extend({reset:function(){this._data=g.create();
this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=d.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var d=this._data,b=d.words,i=d.sigBytes,f=this.blockSize,j=i/(4*f),j=a?e.ceil(j):e.max((j|0)-this._minBufferSize,0),a=j*f,i=e.min(4*a,i);if(a){for(var k=0;k<a;k+=f)this._doProcessBlock(b,k);k=b.splice(0,a);d.sigBytes-=i}return g.create(k,i)},clone:function(){var a=b.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});a.Hasher=i.extend({init:function(){this.reset()},
reset:function(){i.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=i.clone.call(this);a._hash=this._hash.clone();return a},blockSize:16,_createHelper:function(a){return function(d,b){return a.create(b).finalize(d)}},_createHmacHelper:function(a){return function(d,b){return o.HMAC.create(a,b).finalize(d)}}});var o=l.algo={};return l}(Math);
(function(){var e=CryptoJS,c=e.lib,l=c.WordArray,c=c.Hasher,a=[],b=e.algo.SHA1=c.extend({_doReset:function(){this._hash=l.create([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(b,j){for(var f=this._hash.words,k=f[0],d=f[1],i=f[2],e=f[3],h=f[4],c=0;80>c;c++){if(16>c)a[c]=b[j+c]|0;else{var l=a[c-3]^a[c-8]^a[c-14]^a[c-16];a[c]=l<<1|l>>>31}l=(k<<5|k>>>27)+h+a[c];l=20>c?l+((d&i|~d&e)+1518500249):40>c?l+((d^i^e)+1859775393):60>c?l+((d&i|d&e|i&e)-1894007588):l+((d^i^e)-
899497514);h=e;e=i;i=d<<30|d>>>2;d=k;k=l}f[0]=f[0]+k|0;f[1]=f[1]+d|0;f[2]=f[2]+i|0;f[3]=f[3]+e|0;f[4]=f[4]+h|0},_doFinalize:function(){var a=this._data,b=a.words,f=8*this._nDataBytes,c=8*a.sigBytes;b[c>>>5]|=128<<24-c%32;b[(c+64>>>9<<4)+15]=f;a.sigBytes=4*b.length;this._process()}});e.SHA1=c._createHelper(b);e.HmacSHA1=c._createHmacHelper(b)})();
(function(){var e=CryptoJS,c=e.enc.Utf8;e.algo.HMAC=e.lib.Base.extend({init:function(e,a){e=this._hasher=e.create();"string"==typeof a&&(a=c.parse(a));var b=e.blockSize,g=4*b;a.sigBytes>g&&(a=e.finalize(a));for(var j=this._oKey=a.clone(),f=this._iKey=a.clone(),k=j.words,d=f.words,i=0;i<b;i++)k[i]^=1549556828,d[i]^=909522486;j.sigBytes=f.sigBytes=g;this.reset()},reset:function(){var c=this._hasher;c.reset();c.update(this._iKey)},update:function(c){this._hasher.update(c);return this},finalize:function(c){var a=
this._hasher,c=a.finalize(c);a.reset();return a.finalize(this._oKey.clone().concat(c))}})})();var Woogeen=Woogeen||{};Woogeen.authors=["webrtc@intel.com"];Woogeen.version=0.4;Woogeen=Woogeen||{};
Woogeen.Base64=function(){var e,c,l,a,b,g,j,f,k;e="A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9,+,/".split(",");c=[];for(b=0;b<e.length;b+=1)c[e[b]]=b;g=function(d){l=d;a=0};j=function(){var d;if(!l||a>=l.length)return-1;d=l.charCodeAt(a)&255;a+=1;return d};f=function(){if(!l)return-1;for(;;){if(a>=l.length)return-1;var d=l.charAt(a);a+=1;if(c[d])return c[d];if("A"===d)return 0}};k=function(a){a=a.toString(16);1===a.length&&
(a="0"+a);return unescape("%"+a)};return{encodeBase64:function(a){var b,c,f;g(a);a="";b=Array(3);c=0;for(f=!1;!f&&-1!==(b[0]=j());)if(b[1]=j(),b[2]=j(),a+=e[b[0]>>2],-1!==b[1]?(a+=e[b[0]<<4&48|b[1]>>4],-1!==b[2]?(a+=e[b[1]<<2&60|b[2]>>6],a+=e[b[2]&63]):(a+=e[b[1]<<2&60],a+="=",f=!0)):(a+=e[b[0]<<4&48],a+="=",a+="=",f=!0),c+=4,76<=c)a+="\n",c=0;return a},decodeBase64:function(a){var b,c;g(a);a="";b=Array(4);for(c=!1;!c&&-1!==(b[0]=f())&&-1!==(b[1]=f());)b[2]=f(),b[3]=f(),a+=k(b[0]<<2&255|b[1]>>4),
-1!==b[2]?(a+=k(b[1]<<4&255|b[2]>>2),-1!==b[3]?a+=k(b[2]<<6&255|b[3]):c=!0):c=!0;return a}}}(Woogeen);Woogeen=Woogeen||{};
Woogeen.API=function(e){var c,l;c=function(a,b,c,j,f,k,d,i){var o,h,q,p,n,m;void 0===k?(o=e.API.params.service,h=e.API.params.key,f=e.API.params.url+f):(o=k.service,h=k.key,f=k.url+f);""===o||""===h?console.log("ServiceID and Key are required!!"):(k=(new Date).getTime(),q=Math.floor(99999*Math.random()),p=k+","+q,n="MAuth realm=http://webrtc.intel.com,mauth_signature_method=HMAC_SHA1",""!==d&&""!==i&&(n=n+",mauth_username="+d+",mauth_role="+i,p+=","+d+","+i),d=l(p,h),n=n+",mauth_serviceid="+o+",mauth_cnonce="+
q+",mauth_timestamp="+k+",mauth_signature="+d,m=new XMLHttpRequest,m.onreadystatechange=function(){if(m.readyState===4)switch(m.status){case 100:case 200:case 201:case 202:case 203:case 204:case 205:typeof a==="function"&&a(m.responseText);break;default:typeof b==="function"&&b(m.status,m.responseText)}},m.open(c,f,!0),m.setRequestHeader("Authorization",n),void 0!==j)?(m.setRequestHeader("Content-Type","application/json"),m.send(JSON.stringify(j))):m.send()};l=function(a,b){var c;c=CryptoJS.HmacSHA1(a,
b).toString(CryptoJS.enc.Hex);return e.Base64.encodeBase64(c)};return{params:{service:void 0,key:void 0,url:void 0},init:function(a,b,c){e.API.params.service=a;e.API.params.key=b;e.API.params.url=c},createRoom:function(a,b,g,j,f){c(function(a){a=JSON.parse(a);b(a)},g,"POST",{name:a,options:j},"rooms",f)},getRooms:function(a,b,g){c(a,b,"GET",void 0,"rooms",g)},getRoom:function(a,b,g,j){c(b,g,"GET",void 0,"rooms/"+a,j)},updateRoom:function(a,b,g,j,f){c(b,g,"POST",j,"rooms/"+a,f)},deleteRoom:function(a,
b,g,j){c(b,g,"DELETE",void 0,"rooms/"+a,j)},setOptions:function(a,b,g,j,f){c(function(a){g(a)},j,"POST",{room:a,options:b},"rooms/options",f)},createToken:function(a,b,g,j,f,e){c(j,f,"POST",void 0,"rooms/"+a+"/tokens",e,b,g)},createService:function(a,b,g,e,f){c(g,e,"POST",{name:a,key:b},"services/",f)},getServices:function(a,b,g){c(a,b,"GET",void 0,"services/",g)},getService:function(a,b,g,e){c(b,g,"GET",void 0,"services/"+a,e)},deleteService:function(a,b,g,e,f){c(g,e,"DELETE",{forced:b},"services/"+
a,f)},updateService:function(a,b,g,e,f){c(g,e,"POST",b,"services/"+a,f)},getUsers:function(a,b,e,j){c(b,e,"GET",void 0,"rooms/"+a+"/users/",j)},getUser:function(a,b,e,j,f){c(e,j,"GET",void 0,"rooms/"+a+"/users/"+b,f)},deleteUser:function(a,b,e,j){c(e,j,"DELETE",void 0,"rooms/"+a+"/users/"+b)}}}(Woogeen);
module.exports = Woogeen;
